//! Float-literal parser acceptance tests.
//!
//! Reads `tests/lisp/float-literal-corpus.lisp` (generated by SBCL via
//! `tests/lisp/gen-float-corpus.lisp`) and verifies that our float-lexeme
//! parser produces the bitwise-exact `f32` / `f64` SBCL recorded for
//! every entry. Bit equality is required, not approximate equality —
//! IEEE 754 round-to-nearest-even is deterministic, so a single bit
//! difference signals a parser bug.

const std = @import("std");
const zisp = @import("zisp");
const FloatType = zisp.reader.FloatType;
const parseFloatLexeme = zisp.reader.parseFloatLexeme;

const corpus_text = @embedFile("../lisp/float-literal-corpus.lisp");

const Entry = struct {
    lexeme: []const u8,
    type: FloatType,
    bits: u64,
    line_no: u32,
};

const ParseError = error{MalformedCorpusLine};

fn parseHex(text: []const u8) !u64 {
    return std.fmt.parseInt(u64, text, 16);
}

fn parseEntry(line: []const u8, line_no: u32) !?Entry {
    // Trim leading whitespace.
    var i: usize = 0;
    while (i < line.len and (line[i] == ' ' or line[i] == '\t')) : (i += 1) {}
    if (i == line.len) return null; // blank
    if (line[i] == ';') return null; // comment

    const trimmed = line[i..];
    var parts = std.mem.tokenizeAny(u8, trimmed, " \t");
    const lexeme = parts.next() orelse return ParseError.MalformedCorpusLine;
    const type_str = parts.next() orelse return ParseError.MalformedCorpusLine;
    const bits_str = parts.next() orelse return ParseError.MalformedCorpusLine;
    if (parts.next() != null) return ParseError.MalformedCorpusLine;

    const ftype: FloatType = if (std.mem.eql(u8, type_str, "SINGLE"))
        .single
    else if (std.mem.eql(u8, type_str, "DOUBLE"))
        .double
    else
        return ParseError.MalformedCorpusLine;

    const bits = parseHex(bits_str) catch return ParseError.MalformedCorpusLine;

    return .{
        .lexeme = lexeme,
        .type = ftype,
        .bits = bits,
        .line_no = line_no,
    };
}

test "float corpus parses to bitwise-exact SBCL values" {
    var iter = std.mem.splitScalar(u8, corpus_text, '\n');
    var line_no: u32 = 0;
    var entries: u32 = 0;
    while (iter.next()) |line| {
        line_no += 1;
        const entry = (parseEntry(line, line_no) catch |e| {
            std.debug.print(
                "corpus line {d} malformed: {s}\n  >> {s}\n",
                .{ line_no, @errorName(e), line },
            );
            return e;
        }) orelse continue;

        const got = parseFloatLexeme(entry.lexeme) catch |e| {
            std.debug.print(
                "line {d}: parseFloatLexeme({s}) failed: {s}\n",
                .{ entry.line_no, entry.lexeme, @errorName(e) },
            );
            return e;
        };

        const got_bits: u64 = switch (got) {
            .single => |v| @as(u32, @bitCast(v)),
            .double => |v| @as(u64, @bitCast(v)),
        };

        if (std.meta.activeTag(got) != entry.type) {
            std.debug.print(
                "line {d}: {s} — type mismatch: SBCL says {s}, parser says {s}\n",
                .{
                    entry.line_no,
                    entry.lexeme,
                    @tagName(entry.type),
                    @tagName(got),
                },
            );
            return error.TestFailed;
        }

        if (got_bits != entry.bits) {
            std.debug.print(
                "line {d}: {s} — bit mismatch: SBCL {x:0>16} vs parser {x:0>16}\n",
                .{ entry.line_no, entry.lexeme, entry.bits, got_bits },
            );
            return error.TestFailed;
        }
        entries += 1;
    }

    // Acceptance: corpus must have ≥100 entries.
    if (entries < 100) {
        std.debug.print("corpus contained only {d} entries; need ≥100\n", .{entries});
        return error.TestFailed;
    }
}

test "parser rejects empty lexeme" {
    try std.testing.expectError(error.BadFloatLexeme, parseFloatLexeme(""));
}

test "parser rejects lexeme over MAX_LEXEME bytes" {
    var buf: [200]u8 = undefined;
    @memset(&buf, '1');
    buf[1] = '.';
    try std.testing.expectError(error.BadFloatLexeme, parseFloatLexeme(&buf));
}

test "parser rejects garbage with non-marker letter" {
    try std.testing.expectError(error.BadFloatLexeme, parseFloatLexeme("1.0x0"));
}

test "marker letters select correct type" {
    inline for (.{ "1e0", "1f0", "1s0" }) |s| {
        const v = try parseFloatLexeme(s);
        try std.testing.expectEqual(FloatType.single, std.meta.activeTag(v));
    }
    inline for (.{ "1d0", "1l0" }) |s| {
        const v = try parseFloatLexeme(s);
        try std.testing.expectEqual(FloatType.double, std.meta.activeTag(v));
    }
}
