;; Backquote nesting at depth 3 and 4, mixing , and ,@ at
;; multiple levels. Generated by gen-backquote-deep.lisp under
;; SBCL; every expected value is SBCL's. Each form is
;; self-checking and evaluates to T.

(equal (EVAL (EVAL ```(A))) '(A))

(equal (EVAL (EVAL ```(,(+ 1 2)))) '(3))

(equal (EVAL (EVAL ```(,,(+ 1 2)))) '(3))

(equal (EVAL (EVAL ```(,,,(+ 1 2)))) '(3))

(equal (EVAL (EVAL ```(,@'(A B)))) '(A B))

(equal (EVAL (EVAL ```(,,@'((+ 1 1) 5)))) '(2 5))

(equal (EVAL (EVAL ```(,@,'(LIST 1 2)))) '(1 2))

(equal (EVAL (EVAL ```(,@,@'((LIST 1 2))))) '(1 2))

(equal (EVAL (EVAL ```(A ,(LIST 1) C))) '(A (1) C))

(equal (EVAL (EVAL ```(A . ,'(B)))) '(A B))

(equal (EVAL (EVAL ```((,(+ 1 1)) B))) '((2) B))

(equal (EVAL (EVAL ```(,'X ,@'(Y Z)))) '(X Y Z))

(equal (EVAL (EVAL ```(,,'(+ 2 2)))) '(4))

(equal (EVAL (EVAL ```(,',(+ 1 2)))) '(3))

(equal (EVAL (EVAL ```(,@',(LIST 'A 'B)))) '(A B))

(equal (EVAL (EVAL ```(A ,@'(B) ,'C))) '(A B C))

(equal (EVAL (EVAL ```((,@'(1)) (,@'(2 3))))) '((1) (2 3)))

(equal (EVAL (EVAL ```(X ,(CAR '(1 2)) ,@(APPEND '(1) '(2))))) '(X 1 1 2))

(equal (EVAL (EVAL ```(,(+ 1 2) ,,(+ 3 4) ,,,(+ 5 6)))) '(3 7 11))

(equal (EVAL (EVAL ```(,@'((A) (B))))) '((A) (B)))

(equal (EVAL (EVAL ```(A (B ,(+ 1 1))))) '(A (B 2)))

(equal (EVAL (EVAL ```((A . ,'E)))) '((A . E)))

(equal (EVAL (EVAL ```(,@'NIL X ,@'NIL))) '(X))

(equal (EVAL (EVAL ```(,,(LIST '+ 1 2)))) '(3))

(equal (EVAL (EVAL ```((,,@'(1 2)) B))) '((1 2) B))

(equal (EVAL (EVAL ```(,',@'((+ 1 1))))) '((+ 1 1)))

(equal (EVAL (EVAL ```(A . ,,'(LIST 'B)))) '(A B))

(equal (EVAL (EVAL ```(,@,'(LIST 1) ,@,@'((LIST 2 3))))) '(1 2 3))

(equal (EVAL (EVAL ```((X ,,(+ 1 1)) (Y ,@'(2))))) '((X 2) (Y 2)))

(equal (EVAL (EVAL ```(,,@'(1) ,,@'(2 3)))) '(1 2 3))

(equal (EVAL (EVAL (EVAL ````(A)))) '(A))

(equal (EVAL (EVAL (EVAL ````(,(+ 1 2))))) '(3))

(equal (EVAL (EVAL (EVAL ````(,,,,(+ 1 2))))) '(3))

(equal (EVAL (EVAL (EVAL ````(,@'(A B))))) '(A B))

(equal (EVAL (EVAL (EVAL ````(A ,@'(B) C)))) '(A B C))

(equal (EVAL (EVAL (EVAL ````(,'X . ,'(Y))))) '(X Y))

(equal (EVAL (EVAL (EVAL ````((,(+ 2 2)))))) '((4)))

(equal (EVAL (EVAL (EVAL ````(,,@'(5) ,@'(6))))) '(5 6))
