;; Every form here must evaluate to T.

(string= (format nil "~D test~:P" 2) "2 tests")
(string= (format nil "~D test~:P" 1) "1 test")
(string= (format nil "~D famil~:@P" 2) "2 families")
(string= (format nil "~D famil~:@P" 1) "1 family")
(string= (format nil "1 penn~@P" 1) "1 penny")
(string= (format nil "~(HELLO World~)") "hello world")
(string= (format nil "~:(hello world~)") "Hello World")
(string= (format nil "~@(hello world~)") "Hello world")
(string= (format nil "~:@(~S~)" 'ab) "AB")
(string= (format nil "~(~S ~S~)" 'ab 'cd) "ab cd")
(string= (format nil "a~<~%~:; ~>b") "a b")
;; `~@<` hands the block the rest of the argument list, where `~<`
;; would take one list argument.
(string= (format nil "~@<~@{~S~^, ~:_~}~:>" 1 2) "1, 2")
(string= (format nil "a~
      b") "ab")
(string= (format nil "a~:
      b") "a      b")
(string= (format nil "a~@
      b") (concatenate 'string "a" (string #\Newline) "b"))
(string= (format nil "~W" '(1 "x")) "(1 \"x\")")
(string= (format nil "a~_b") "ab")
(string= (format nil "~2Ia") "a")
(string= (format nil "~:[no~;yes~]" nil) "no")
(string= (format nil "~@[~a~]" 5) "5")
(string= (format nil "~{~a-~}" '(1 2)) "1-2-")
(string= (format nil "~?" "~a" '(7)) "7")
(string= (format nil "~{~}" (formatter "~A") '(1 2 3)) "123")
(string= (format nil "~2{~}" (formatter "~A") '(1 2 3)) "12")
(string= (format nil "~:{~}" (formatter "~A") '((1 2) (3))) "13")
(string= (format nil "~@{~}" (formatter "<~A>") 1 2) "<1><2>")
(string= (format nil "~{FOO~:}" nil) "FOO")
(string= (format nil "~0{FOO~:}" nil) "")
(string= (format nil "~v{~A~}" nil '(1 2 3)) "123")
(string= (format nil "~1@{~A~}|~A" 1 2) "1|2")
(string= (format nil "~?" (formatter "~A~A") '(5 6)) "56")
(string= (format nil "~@?|~A" (formatter "~A") 1 2) "1|2")
(let (left)
  (with-output-to-string (s)
    (setq left (funcall (formatter "~:@{~0:^~A~}") s '(1) '(2))))
  (equal left '((2))))
(eq (handler-case (format nil "~{~}" 7 nil) (type-error () :rejected)) :rejected)
(eq (handler-case (format nil "~{~}" (lambda (stream &rest args) (declare (ignore stream args)) '(1 2 3)) '(1))
      (program-error () :rejected))
    :rejected)
(string= (let ((*print-circle* t))
           (format nil "~:<~@{~A~^ ~}~:>" (let ((x (list 0))) (setf (cdr x) x) x)))
         "#1=(0 . #1#)")
(string= (let ((*print-circle* t))
           (format nil "~:<~@{~A~^ ~}~:>" (let ((x (list 0))) (list x x))))
         "(#1=(0) #1#)")
(string= (let ((*print-circle* t))
           (format nil "~:<~@{~A~^ ~}~:>" (let ((x (list 0))) (cons x x))))
         "(#1=(0) . #1#)")
(string= (format nil "~:<~@{~A~^ ~}~:>" '(1 2 . 3)) "(1 2 . 3)")
(string= (let ((*print-length* 2)) (format nil "~:<~@{~A~^ ~}~:>" '(1 2 3 4))) "(1 2 ...)")
(string= (format nil "~:<~@{~A~^ ~}~:>" '(1 2)) "(1 2)")
(eq (handler-case (format nil "~:<~A ~A~:>" '(1)) (program-error () :rejected)) :rejected)
