;;;; gen-float-corpus.lisp — emit tests/lisp/float-literal-corpus.lisp
;;;;
;;;; Run via:
;;;;   sbcl --script tests/lisp/gen-float-corpus.lisp > tests/lisp/float-literal-corpus.lisp
;;;;
;;;; The corpus pins zisp's float-lexeme parser to the bitwise-exact f32/f64
;;;; values SBCL produces. ROADMAP 1.1.6 acceptance: each entry round-trips
;;;; through our parser to the same bit pattern SBCL stored.
;;;;
;;;; SBCL version is recorded by zig build CI; pinning is documented in
;;;; docs/perf-baseline.md (Phase 0 docs scaffold).

(defun single-bits (x)
  (declare (type single-float x))
  (ldb (byte 32 0) (sb-kernel:single-float-bits x)))

(defun double-bits (x)
  (declare (type double-float x))
  (let ((hi (ldb (byte 32 0) (sb-kernel:double-float-high-bits x)))
        (lo (sb-kernel:double-float-low-bits x)))
    (logior (ash hi 32) lo)))

(defun float-type-tag (x)
  (etypecase x
    (single-float :SINGLE)
    (double-float :DOUBLE)))

(defun float-bits (x)
  (etypecase x
    (single-float (single-bits x))
    (double-float (double-bits x))))

;; Each lexeme is exactly the source text the tokenizer hands us.
;; *read-default-float-format* defaults to single-float in both SBCL and
;; zisp, so unmarked lexemes (e.g. "1.5") read as single-float on both sides.
(defparameter *cases*
  '(;; --- 1. zeros and small unmarked (single-float default) ---
    "0.0" "-0.0" "+0.0" "0.5" "-0.5" "1.0" "-1.0" "+1.0"
    "2.0" "0.25" "0.125" "1.5" "-1.5" "100.0" "1000.0" ".5"
    ".25" ".125" ".1" "10.0" "-10.0" "0.001" "1.000" "1.0000001"
    "1.0000002" "0.99999994"

    ;; --- 2. unmarked with exponent (single-float by default) ---
    "1e0" "1e1" "1e-1" "1e+1" "1e10" "-1e10" "1.5e2" "1.5e-2"
    "1.5e+2" "6.022e23" "1.602176634e-19" "3.4028235e38"
    "1.17549435e-38" "1.4e-45"

    ;; --- 3. explicit single-float marker (s/S, f/F) ---
    "1.0f0" "2.0f0" "1f0" "1f10" "-1f-10" "0.1f0" "1.0000001f0"
    "1.0s0" "2.0s0" "1s0" "1s-1" "1.5s2" "3.4028235s38"

    ;; --- 4. double-float marker (d/D) ---
    "1.0d0" "-1.0d0" "0.0d0" "-0.0d0" "0.5d0" "0.1d0" "0.2d0"
    "0.3d0" "3.14d0" "-3.14d0" "1d0" "1d10" "-1d-10" "1.5d2"
    "6.022d23" "1.602176634d-19" "1.234567890123456d0"
    "1.7976931348623157d308" "2.2250738585072014d-308"
    "5d-324" "4.9d-324" "1d-300" "1d300" "1d-100" "1d100"
    "1.0000001d0" "1.00000000000000022d0"

    ;; --- 5. long-float marker (l/L) — Lisp permits long = double ---
    "1.0l0" "1.5l-10" "1l0" "1l10" "-1l-10" "3.14l0"

    ;; --- 6. signed exponents and leading-dot variants ---
    "+1.5" "-1.5e+5" "1.5e-5" "1.5d+5" "1.5d-5" ".5d0" ".25d0"
    "+1.0d10" "-1.0d10"

    ;; --- 7. precision-edge / round-half-to-even territory ---
    "0.1" "0.2" "0.3" "0.7" "1.1" "1.2" "1.3"
    "1.234567f0" "1.234567890123456789d0"))

(format t ";; tests/lisp/float-literal-corpus.lisp~%")
(format t ";; AUTO-GENERATED by tests/lisp/gen-float-corpus.lisp via SBCL ~A.~%"
        (lisp-implementation-version))
(format t ";; Each non-comment line: LEXEME TYPE BITS-HEX~%")
(format t ";;   LEXEME — float literal as the tokenizer sees it~%")
(format t ";;   TYPE — :SINGLE or :DOUBLE~%")
(format t ";;   BITS-HEX — IEEE 754 bit pattern (uppercase hex, no prefix)~%")
(format t ";; Lines starting with `;` are comments.~%")
(format t ";;~%")
(format t ";; ROADMAP 1.1.6: each parses to the bitwise-exact f32/f64 SBCL produces.~%")
(format t ";;~%")
(let ((n 0))
  (dolist (lexeme *cases*)
    (let* ((val (read-from-string lexeme))
           (type (float-type-tag val))
           (bits (float-bits val))
           (width (if (eq type :SINGLE) 8 16)))
      (format t "~A ~A ~V,'0X~%" lexeme type width bits)
      (incf n)))
  (format *error-output* ";; emitted ~D entries~%" n))
