;; Regenerates backquote-deep.lisp. Run under SBCL from the repo root:
;;
;;   sbcl --script tests/lisp/gen-backquote-deep.lisp > tests/lisp/backquote-deep.lisp
;;
;; Each case is (depth template). The template is evaluated depth times to
;; reach a plain value; the emitted corpus form performs depth-1 explicit
;; evals since reading the literal template supplies the first round. All
;; unquoted subforms are closed (no free variables), because eval uses the
;; null lexical environment.

(defparameter *cases*
  '((3 ```(a))
    (3 ```(,(+ 1 2)))
    (3 ```(,,(+ 1 2)))
    (3 ```(,,,(+ 1 2)))
    (3 ```(,@'(a b)))
    (3 ```(,,@'((+ 1 1) 5)))
    (3 ```(,@,'(list 1 2)))
    (3 ```(,@,@'((list 1 2))))
    (3 ```(a ,(list 1) c))
    (3 ```(a . ,'(b)))
    (3 ```((,(+ 1 1)) b))
    (3 ```(,'x ,@'(y z)))
    (3 ```(,,'(+ 2 2)))
    (3 ```(,',(+ 1 2)))
    (3 ```(,@',(list 'a 'b)))
    (3 ```(a ,@'(b) ,'c))
    (3 ```((,@'(1)) (,@'(2 3))))
    (3 ```(x ,(car '(1 2)) ,@(append '(1) '(2))))
    (3 ```(,(+ 1 2) ,,(+ 3 4) ,,,(+ 5 6)))
    (3 ```(,@'((a) (b))))
    (3 ```(a (b ,(+ 1 1))))
    (3 ```((a . ,'e)))
    (3 ```(,@'() x ,@'()))
    (3 ```(,,(list '+ 1 2)))
    (3 ```((,,@'(1 2)) b))
    (3 ```(,',@'((+ 1 1))))
    (3 ```(a . ,,'(list 'b)))
    (3 ```(,@,'(list 1) ,@,@'((list 2 3))))
    (3 ```((x ,,(+ 1 1)) (y ,@'(2))))
    (3 ```(,,@'(1) ,,@'(2 3)))
    (4 ````(a))
    (4 ````(,(+ 1 2)))
    (4 ````(,,,,(+ 1 2)))
    (4 ````(,@'(a b)))
    (4 ````(a ,@'(b) c))
    (4 ````(,'x . ,'(y)))
    (4 ````((,(+ 2 2))))
    (4 ````(,,@'(5) ,@'(6)))))

(format t ";; Backquote nesting at depth 3 and 4, mixing , and ,@ at~%")
(format t ";; multiple levels. Generated by gen-backquote-deep.lisp under~%")
(format t ";; SBCL; every expected value is SBCL's. Each form is~%")
(format t ";; self-checking and evaluates to T.~%")
(dolist (case *cases*)
  (let ((depth (first case))
        (template (second case)))
    (let ((val template))
      (dotimes (i depth) (setf val (eval val)))
      (let ((wrapped template))
        (dotimes (i (1- depth)) (setf wrapped (list 'eval wrapped)))
        (format t "~%(equal ~s '~s)~%" wrapped val)))))
