;; Every form here must evaluate to T.

(equal (let ((seen nil)) (dolist (x '(1 2 3)) (push x seen)) seen) '(3 2 1))
(null (dolist (x '(1 2))))
(eql (dolist (x '(1 2) :done) x) :done)
(let ((last :unset))
  (dolist (x '(1 2) (setq last x)))
  (null last))
(eql (dolist (x '(1 2 3)) (when (= x 2) (return x))) 2)
(equal (let ((seen nil)) (dotimes (i 3) (push i seen)) seen) '(2 1 0))
(eql (dotimes (i 3 :done)) :done)
(eql (dotimes (i 5) (when (= i 2) (return i))) 2)
(null (dotimes (i 0)))
(equal (do ((i 0 (1+ i)) (acc nil (cons i acc))) ((= i 3) acc)) '(2 1 0))
(eql (do* ((i 0 (1+ i)) (j i (1+ i))) ((= i 2) j)) 3)
(eql (do ((i 0 (1+ i))) (nil) (when (= i 4) (return i))) 4)
(equal (let ((a 1) (b 2)) (psetq a b b a) (list a b)) '(2 1))
(equal (let ((a 1) (b 2)) (setq a b b a) (list a b)) '(2 2))
(eql (do ((i 0 (1+ i)) (total 0 (+ total i))) ((= i 4) total)) 6)
(let ((steps 0))
  (do ((i 0 (1+ i))) ((= i 3)) (declare (ignore i)) (setq steps (1+ steps)))
  (eql steps 3))
