;; Every form here must evaluate to T.

(equal (last '(1 2 3)) '(3))
(equal (last '(1 2 3) 2) '(2 3))
(equal (last '(1 2 3) 9) '(1 2 3))
(equal (butlast '(1 2 3)) '(1 2))
(equal (butlast '(1 2 3) 2) '(1))
(null (butlast '(1)))
(equal (let ((l (list 1 2 3))) (nbutlast l) l) '(1 2))
(equal (copy-list '(1 2 3)) '(1 2 3))
(let ((l (list 1 2))) (not (eq (copy-list l) l)))
(equal (copy-list '(1 . 2)) '(1 . 2))
(equal (copy-tree '((1 2) (3))) '((1 2) (3)))
(equal (copy-alist '((:a . 1))) '((:a . 1)))
(eql (list-length '(1 2 3)) 3)
(null (list-length (let ((l (list 1 2))) (rplacd (cdr l) l) l)))
(equal (make-list 3 :initial-element :x) '(:x :x :x))
(null (make-list 0))
(equal (nconc (list 1) nil (list 2 3)) '(1 2 3))
(null (nconc nil nil))
(equal (revappend '(1 2) '(3)) '(2 1 3))
(equal (nreconc (list 1 2) (list 3)) '(2 1 3))
(equal (ldiff '(1 2 3) '(3)) '(1 2 3))
(let ((l (list 1 2 3))) (equal (ldiff l (cddr l)) '(1 2)))
(let ((l (list 1 2 3))) (tailp (cddr l) l))
(null (tailp '(9) '(1 2)))
(eql (getf '(:a 1 :b 2) :b) 2)
(eql (getf '(:a 1) :missing :default) :default)
(equal (multiple-value-list (get-properties '(:a 1 :b 2) '(:b))) '(:b 2 (:b 2)))
(let ((plist (list :a 1 :b 2))) (and (remf plist :a) (equal plist '(:b 2))))
(let ((plist (list :a 1))) (null (remf plist :missing)))
(equal (acons :k :v nil) '((:k . :v)))
(equal (pairlis '(:a) '(1)) '((:a . 1)))
(equal (member-if #'evenp '(1 3 4 5)) '(4 5))
(equal (member-if-not #'evenp '(2 4 5)) '(5))
(equal (assoc-if #'evenp '((1 . :a) (2 . :b))) '(2 . :b))
(equal (assoc-if-not #'evenp '((2 . :a) (1 . :b))) '(1 . :b))
(equal (rassoc 2 '((:a . 1) (:b . 2))) '(:b . 2))
(equal (rassoc-if #'evenp '((:a . 1) (:b . 2))) '(:b . 2))
(equal (rassoc-if-not #'evenp '((:a . 2) (:b . 1))) '(:b . 1))
(equal (adjoin 3 '(1 2)) '(3 1 2))
(equal (adjoin 1 '(1 2)) '(1 2))
(equal (adjoin '(1) '((1)) :test #'equal) '((1)))
(equal (sort (copy-list (union '(1 2) '(2 3))) #'<) '(1 2 3))
(equal (sort (copy-list (nunion '(1) '(2))) #'<) '(1 2))
(equal (intersection '(1 2 3) '(2 3 4)) '(3 2))
(equal (nintersection '(1 2) '(2)) '(2))
(equal (set-difference '(1 2 3) '(2)) '(3 1))
(equal (nset-difference '(1 2) '(2)) '(1))
(equal (sort (copy-list (set-exclusive-or '(1 2) '(2 3))) #'<) '(1 3))
(equal (nset-exclusive-or '(1) '(1)) nil)
(subsetp '(1 2) '(1 2 3))
(null (subsetp '(1 9) '(1 2)))
(equal (maplist #'car '(1 2 3)) '(1 2 3))
(equal (maplist #'length '(1 2 3)) '(3 2 1))
(equal (mapl #'identity '(1 2)) '(1 2))
(equal (mapcon #'copy-list '(1 2)) '(1 2 2))
(tree-equal '(1 (2 3)) '(1 (2 3)))
(null (tree-equal '(1) '(2)))
(tree-equal '(1 2) '(1.0 2.0) :test (lambda (a b) (if (and (numberp a) (numberp b)) (= a b) (eql a b))))
(equal (subst :new 2 '(1 (2 3))) '(1 (:new 3)))
(equal (nsubst :new 2 (list 1 2)) '(1 :new))
(equal (subst-if :new (lambda (x) (and (integerp x) (evenp x))) '(1 2)) '(1 :new))
(equal (subst-if-not :new #'consp '(1 . 2)) '(:new . :new))
(equal (sublis '((a . 1) (b . 2)) '(a (b))) '(1 (2)))
(equal (nsublis '((a . 1)) '(a)) '(1))
(equal (remove-duplicates '(1 2 1 3)) '(2 1 3))
(equal (remove-duplicates '(1 2 1 3) :from-end t) '(1 2 3))
(equal (remove-duplicates "abca") "bca")
(equal (delete-duplicates (list 1 1 2)) '(1 2))
(equal (rest '(1 2)) '(2))
(some #'evenp '(1 2 3))
(null (some #'evenp '(1 3)))
(some #'< '(1 2) '(2 1))
(every #'evenp '(2 4))
(null (every #'evenp '(2 3)))
(every #'< '(1 2) '(3 4))
(notany #'evenp '(1 3))
(notevery #'evenp '(2 3))
(some #'evenp #(1 2))
(every #'characterp "ab")
