;; Every form here must evaluate to T.

(equal (loop for x in '(1 2 3) collect (* x x)) '(1 4 9))
(equal (loop for x on '(1 2 3) collect x) '((1 2 3) (2 3) (3)))
(equal (loop for x on '(:a 1 :b 2) by #'cddr collect (car x)) '(:a :b))
(equal (loop for i from 0 below 3 collect i) '(0 1 2))
(equal (loop for i from 1 to 7 by 3 collect i) '(1 4 7))
(equal (loop for i from 5 downto 1 by 2 collect i) '(5 3 1))
(equal (loop for i from 5 above 2 collect i) '(5 4 3))
(equal (loop for i downfrom 3 to 1 collect i) '(3 2 1))
(equal (loop for x across #(1 2 3) collect x) '(1 2 3))
(equal (loop for x = 1 then (* x 2) repeat 4 collect x) '(1 2 4 8))
(equal (loop for (a . b) in '((1 . 2) (3 . 4)) collect (+ a b)) '(3 7))
(equal (loop for (a b) in '((1 2) (3 4)) collect (list b a)) '((2 1) (4 3)))
(equal (loop for i from 0 for e in '(a b) collect (list i e)) '((0 a) (1 b)))
(eql (loop repeat 3 count t) 3)
(eql (loop for i from 1 to 4 sum i) 10)
(eql (loop for i in '(3 1 2) maximize i) 3)
(eql (loop for i in '(3 1 2) minimize i) 1)
(null (loop for i in '() maximize i))
(equal (loop for i in '(1 2) append (list i i)) '(1 1 2 2))
(equal (loop for i in '(1 2) nconc (list i i)) '(1 1 2 2))
(equal (loop for i from 1 to 5 when (evenp i) collect i) '(2 4))
(equal (loop for i from 1 to 5 unless (evenp i) collect i) '(1 3 5))
(equal (loop for i from 1 to 4 if (evenp i) collect i else collect (- i))
       '(-1 2 -3 4))
(equal (loop for i from 1 to 3 collect i into evens count t into how-many
             finally (return (list evens how-many)))
       '((1 2 3) 3))
(equal (loop with a = 1 with b = 2 return (list a b)) '(1 2))
(equal (loop for i from 1 while (< i 3) collect i) '(1 2))
(equal (loop for i from 1 until (> i 2) collect i) '(1 2))
(null (loop for i from 1 to 5 always (< i 3)))
(loop for i from 1 to 5 never (> i 9))
(eql (loop for i in '(1 2 3) thereis (and (evenp i) i)) 2)
(equal (loop initially (list :start) for i from 1 to 2 collect i finally (return :done))
       :done)
(let ((seen nil))
  (loop for i from 1 to 3 do (push i seen))
  (equal seen '(3 2 1)))
(let ((table (make-hash-table)))
  (setf (gethash :only table) 7)
  (equal (loop for k being the hash-keys of table collect k) '(:only)))
(let ((table (make-hash-table)))
  (setf (gethash :only table) 7)
  (equal (loop for v being the hash-values of table collect v) '(7)))
(let ((table (make-hash-table)))
  (setf (gethash :only table) 7)
  (equal (loop for k being the hash-keys of table using (hash-value v) collect (list k v))
         '((:only 7))))
(eql (loop named outer for i from 1 do (return-from outer i)) 1)
(let ((count 0))
  (loop (setq count (1+ count)) (when (= count 3) (return)))
  (eql count 3))
(equal (loop for i from 1 to 4 collect i collect (- i))
       '(1 -1 2 -2 3 -3 4 -4))
(equal (loop for outer from 1 to 2
             append (loop for inner from 1 to 2 collect (list outer inner)))
       '((1 1) (1 2) (2 1) (2 2)))
