;; Every form here must evaluate to T.

(equalp '#*0101 (make-array 4 :element-type 'bit :initial-contents '(0 1 0 1)))
(eql (length '#*) 0)
(eql (aref '#*10 0) 1)
(string= (write-to-string '#*1100) "#*1100")
(eql '#.(+ 1 2) 3)
(equal (list #.(ash 1 4)) '(16))
(string= "a\nb" "anb")
(string= "\#\\" (concatenate 'string (string #\#) (string #\\)))
(eql (length "a\\b") 3)
(string= (symbol-name '#:|a|) "a")
(string= (symbol-name '#:||) "")
(string= (symbol-name ':|Ab|) "Ab")
(string= (symbol-name 'a|b|C) "AbC")
(null (symbol-package '#:foo))
(readtablep *readtable*)
(readtablep (copy-readtable))
(eq (readtable-case *readtable*) :upcase)
(let ((copy (copy-readtable)))
  (setf (readtable-case copy) :preserve)
  (and (eq (readtable-case copy) :preserve)
       (eq (readtable-case *readtable*) :upcase)))
(not (eq (copy-readtable) (copy-readtable)))
