;; Every form here must evaluate to T.

(equal (replace (list 1 2 3) '(9 8)) '(9 8 3))
(equal (replace (list 1 2 3) '(9) :start1 1) '(1 9 3))
(equal (replace (list 1 2 3) '(7 8 9) :start2 1 :end2 2) '(8 2 3))
(string= (replace (make-string 3 :initial-element #\.) "ab" :start1 1) ".ab")
(let ((v (vector 1 2 3))) (equalp (replace v v :start1 1 :start2 0) #(1 1 2)))
(equal (fill (list 1 2 3) :x) '(:x :x :x))
(equal (fill (list 1 2 3) :x :start 1 :end 2) '(1 :x 3))
(null (mismatch '(1 2) '(1 2)))
(eql (mismatch '(1 2) '(1 3)) 1)
(eql (mismatch "abc" "ab") 2)
(eql (mismatch "abc" "bc" :from-end t) 1)
(eql (mismatch '(1 2 3) '(9 2 3) :start1 1 :start2 1) nil)
(eql (search "bc" "abcd") 1)
(null (search "zz" "abcd"))
(eql (search "a" "aaa" :from-end t) 2)
(eql (search "" "abc") 0)
(equal (make-sequence 'list 2 :initial-element :x) '(:x :x))
(string= (make-sequence 'string 2 :initial-element #\a) "aa")
(equalp (make-sequence 'vector 2 :initial-element 0) #(0 0))
(equal (substitute-if 0 #'evenp '(1 2 3 4)) '(1 0 3 0))
(equal (substitute-if 0 #'evenp '(2 4 6) :count 2) '(0 0 6))
(equal (substitute-if 0 #'evenp '(2 4 6) :count 1 :from-end t) '(2 4 0))
(equal (substitute-if-not 0 #'evenp '(1 2)) '(0 2))
(equal (nsubstitute-if 0 #'evenp (list 1 2)) '(1 0))
(equal (nsubstitute-if-not 0 #'evenp (list 1 2)) '(0 2))
(equal (let ((l (list 1 2 3))) (setf (subseq l 1 2) '(:x)) l) '(1 :x 3))
(string= (let ((s (make-string 4 :initial-element #\.))) (setf (subseq s 1 3) "ab") s) ".ab.")
(eql (funcall (constantly 5) 1 2 3) 5)
(funcall (complement #'evenp) 3)
(null (funcall (complement #'evenp) 2))
